[package]
name = "musicplayer"
version = "0.1.0"
edition = "2021"

[dependencies]
iced = { version = "0.13.1", features = ["tokio"] }
rodio = { git = "https://github.com/RustAudio/rodio.git", features = ["symphonia", "symphonia-mp3"] }
tokio = { version = "1.44.0", features = ["full"] }
