[package]
name = "musicplayer"
version = "0.1.0"
edition = "2021"

[dependencies]
iced = { version = "0.13.1", features = ["tokio"] }
rodio = "0.20.1"
tokio = { version = "1.44.0", features = ["full"] }
